### ISSUE TITLE
Add a dropdown to select the version of forc

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway-playground#10]
@kayagokalp Suggested: having a drop-down or something to select desired forc/compiler version could be cool.

**Comment by kayagokalp** [comment]
closing #9 in favor of this one

**Comment by sdankel** [comment]
Depends on https://github.com/FuelLabs/sway-playground/issues/22

**Comment by sdankel** [comment]
Closed by https://github.com/FuelLabs/sway-playground/pull/24
