### ISSUE TITLE
Dark mode for sway playground!

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway-playground#45]
As a dark mode user myself, I would greatly appreciate it! The website should detect if the user has dark mode set in their browser, and adjust the colors accordingly.

**Comment by mabsattar** [comment]
Hi, i'd like to tackle this, can you please assign me.

**Comment by iliya-slpr** [comment]
Hi, i'd like to tackle this, can you please assign me.

**Comment by dicethedev** [comment]
@mabsattar still fixing this issue?

**Comment by dicethedev** [comment]
> @dicethedev hi, yes i'm working on it

Alright. Kudos to you @mabsattar
