### ISSUE TITLE
Include code sharing 

### ISSUE THREAD

**Issue by calldelegation** [FuelLabs/sway-playground#78]
https://sway-by-example-4tic94a95-fuel-labs.vercel.app/hello-world

<img width="1920" alt="Screenshot 2024-05-08 at 6 57 02 PM (2)" src="https://github.com/FuelLabs/sway-playground/assets/106365423/4ca55c65-9843-4a87-aae3-102918cdb5da">

Would love to have a feature that replicates a "Try on remix" where it automatically imports the code into the sway playground.

<img width="1920" alt="Screenshot 2024-05-08 at 6 58 22 PM (2)" src="https://github.com/FuelLabs/sway-playground/assets/106365423/af5378a6-abf9-4ed6-89c8-73332dd52e91">

**Comment by sdankel** [comment]
We can take a similar approach to rust playground. See https://github.com/FuelLabs/sway-playground/pull/76/files#r1594821382
