### ISSUE TITLE
LSP inlay hints not going away

### ISSUE THREAD

**Issue by alfiedotwtf** [FuelLabs/sway-playground#95]
I have the following on my local playground:

![Screenshot 2024-08-21 at 16 55 33](https://github.com/user-attachments/assets/e08425a0-79bb-4f03-99d8-4b5b7e88b643)

If I then type `hello` below height, I get:

![Screenshot 2024-08-21 at 16 55 52](https://github.com/user-attachments/assets/8c029218-63ff-45b6-90aa-9ad4e0be0cec)

Followed by deleting the `hello` text, I'm left with:

![Screenshot 2024-08-21 at 16 56 08](https://github.com/user-attachments/assets/5846799e-2ab5-48b3-9e3e-bcf360de4ffc)

Up until about 5 minutes ago I was getting javascript errors in the console, but now I can't reproduce the errors (but I can reproduce the hints not going away).

**Comment by sdankel** [comment]
Hey @alfiedotwtf, this is not actually part of LSP, this UI is the graphql plaground which is a 3rd party tool maintained by Apollo. You might want to open this issue on https://github.com/graphql/graphql-playground, although the client is likely not on the latest version.
